import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]
[window]
startup_mode = "Fullscreen"

[mouse] 
  hide_when_typing = true

[env]

TERM = "xterm-256color"

[keyboard] 
  bindings = [
    { key = "F11", action = "ToggleFullscreen" },
  ]

[font]
  size = 18.0
  normal = {family = "JetBrainsMono Nerd Font",  style = "Regular"}
  bold = {family = "JetBrainsMono Nerd Font", style = "Bold"}
  bold_italic = {  family = "JetBrainsMono Nerd Font" }
  italic = {  family = "JetBrainsMono Nerd Font", style = "Italic"}

